export const config_descriptions = [
	//ver 0.53
	{
		name: 'border_size',
		path: 'general',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 20',
		description: 'size of the border around windows',
	},
	{
		name: 'gaps_in',
		path: 'general',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"5"',
		description: 'gaps between windowssupports css style gaps (top, right, bottom, left -> 5 10 15 20)',
	},
	{
		name: 'gaps_out',
		path: 'general',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"20"',
		description: 'gaps between windows and monitor edgessupports css style gaps (top, right, bottom, left -> 5 10 15 20)',
	},
	{
		name: 'float_gaps',
		path: 'general',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"0"',
		description:
			'gaps between windows and monitor edges for floating windowssupports css style gaps (top, right, bottom, left -> 5 10 15 20). -1 means default  gaps_in/gaps_out0 means no gaps',
	},
	{
		name: 'gaps_workspaces',
		path: 'general',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 100',
		description: 'gaps between workspaces. Stacks with gaps_out.',
	},
	{
		name: 'col.inactive_border',
		path: 'general',
		type: 'CONFIG_OPTION_GRADIENT',
		data: '"0xff444444"',
		description: 'border color for inactive windows',
	},
	{
		name: 'col.active_border',
		path: 'general',
		type: 'CONFIG_OPTION_GRADIENT',
		data: '"0xffffffff"',
		description: 'border color for the active window',
	},
	{
		name: 'col.nogroup_border',
		path: 'general',
		type: 'CONFIG_OPTION_GRADIENT',
		data: '"0xffffaaff"',
		description: 'inactive border color for window that cannot be added to a group (see denywindowfromgroup dispatcher)',
	},
	{
		name: 'col.nogroup_border_active',
		path: 'general',
		type: 'CONFIG_OPTION_GRADIENT',
		data: '"0xffff00ff"',
		description: 'active border color for window that cannot be added to a group',
	},
	{
		name: 'layout',
		path: 'general',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"dwindle"',
		description: 'which layout to use. [dwindle/master]',
	},
	{
		name: 'no_focus_fallback',
		path: 'general',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'if true, will not fall back to the next available window when moving focus in a direction where no window was found',
	},
	{
		name: 'resize_on_border',
		path: 'general',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enables resizing windows by clicking and dragging on borders and gaps',
	},
	{
		name: 'extend_border_grab_area',
		path: 'general',
		type: 'CONFIG_OPTION_INT',
		data: '15, 0, 100',
		description: 'extends the area around the border where you can click and drag on, only used when general:resize_on_border is on.',
	},
	{
		name: 'hover_icon_on_border',
		path: 'general',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'show a cursor icon when hovering over borders, only used when general:resize_on_border is on.',
	},
	{
		name: 'allow_tearing',
		path: 'general',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'master switch for allowing tearing to occur. See the Tearing page.',
	},
	{
		name: 'resize_corner',
		path: 'general',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 4',
		description:
			'force floating windows to use a specific corner when being resized (1-4 going clockwise from top left, 0 to disable)',
	},
	{
		name: 'enabled',
		path: 'general:snap',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enable snapping for floating windows',
	},
	{
		name: 'window_gap',
		path: 'general:snap',
		type: 'CONFIG_OPTION_INT',
		data: '10, 0, 100',
		description: 'minimum gap in pixels between windows before snapping',
	},
	{
		name: 'monitor_gap',
		path: 'general:snap',
		type: 'CONFIG_OPTION_INT',
		data: '10, 0, 100',
		description: 'minimum gap in pixels between window and monitor edges before snapping',
	},
	{
		name: 'border_overlap',
		path: 'general:snap',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: "if true, windows snap such that only one border's worth of space is between them",
	},
	{
		name: 'respect_gaps',
		path: 'general:snap',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if true, snapping will respect gaps between windows',
	},
	{
		name: 'modal_parent_blocking',
		path: 'general',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'if true, parent windows of modals will not be interactive.',
	},
	{
		name: 'locale',
		path: 'general',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description: 'overrides the system locale',
	},
	{
		name: 'rounding',
		path: 'decoration',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 20',
		description: "rounded corners' radius (in layout px)",
	},
	{
		name: 'rounding_power',
		path: 'decoration',
		type: 'CONFIG_OPTION_FLOAT',
		data: '2, 2, 10',
		description: 'rounding power of corners (2 is a circle)',
	},
	{
		name: 'active_opacity',
		path: 'decoration',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 0, 1',
		description: 'opacity of active windows. [0.0 - 1.0]',
	},
	{
		name: 'inactive_opacity',
		path: 'decoration',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 0, 1',
		description: 'opacity of inactive windows. [0.0 - 1.0]',
	},
	{
		name: 'fullscreen_opacity',
		path: 'decoration',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 0, 1',
		description: 'opacity of fullscreen windows. [0.0 - 1.0]',
	},
	{
		name: 'enabled',
		path: 'decoration:shadow',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'enable drop shadows on windows',
	},
	{
		name: 'range',
		path: 'decoration:shadow',
		type: 'CONFIG_OPTION_INT',
		data: '4, 0, 100',
		description: 'Shadow range (size) in layout px',
	},
	{
		name: 'render_power',
		path: 'decoration:shadow',
		type: 'CONFIG_OPTION_INT',
		data: '3, 1, 4',
		description: 'in what power to render the falloff (more power, the faster the falloff) [1 - 4]',
	},
	{
		name: 'sharp',
		path: 'decoration:shadow',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether the shadow should be sharp or not. Akin to an infinitely high render power.',
	},
	{
		name: 'ignore_window',
		path: 'decoration:shadow',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'if true, the shadow will not be rendered behind the window itself, only around it.',
	},
	{
		name: 'color',
		path: 'decoration:shadow',
		type: 'CONFIG_OPTION_COLOR',
		data: '0xee1a1a1a',
		description: "shadow's color. Alpha dictates shadow's opacity.",
	},
	{
		name: 'color_inactive',
		path: 'decoration:shadow',
		type: 'CONFIG_OPTION_COLOR',
		data: null,
		description: 'inactive shadow color. (if not set, will fall back to col.shadow)',
	},
	{
		name: 'offset',
		path: 'decoration:shadow',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{}, {-250, -250}, {250, 250}',
		description: "shadow's rendering offset.",
	},
	{
		name: 'scale',
		path: 'decoration:shadow',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 0, 1',
		description: "shadow's scale. [0.0 - 1.0]",
	},
	{
		name: 'dim_modal',
		path: 'decoration',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'enables dimming of parents of modal windows',
	},
	{
		name: 'dim_inactive',
		path: 'decoration',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enables dimming of inactive windows',
	},
	{
		name: 'dim_strength',
		path: 'decoration',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.5, 0, 1',
		description: 'how much inactive windows should be dimmed [0.0 - 1.0]',
	},
	{
		name: 'dim_special',
		path: 'decoration',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.2, 0, 1',
		description: 'how much to dim the rest of the screen by when a special workspace is open. [0.0 - 1.0]',
	},
	{
		name: 'dim_around',
		path: 'decoration',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.4, 0, 1',
		description: 'how much the dimaround window rule should dim by. [0.0 - 1.0]',
	},
	{
		name: 'screen_shader',
		path: 'decoration',
		type: 'CONFIG_OPTION_STRING_LONG',
		data: '""',
		description:
			'screen_shader a path to a custom shader to be applied at the end of rendering. See examples/screenShader.frag for an example.',
	},
	{
		name: 'border_part_of_window',
		path: 'decoration',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether the border should be treated as a part of the window.',
	},
	{
		name: 'enabled',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'enable kawase window background blur',
	},
	{
		name: 'size',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_INT',
		data: '8, 0, 100',
		description: 'blur size (distance)',
	},
	{
		name: 'passes',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 10',
		description: 'the amount of passes to perform',
	},
	{
		name: 'ignore_opacity',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'make the blur layer ignore the opacity of the window',
	},
	{
		name: 'new_optimizations',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description:
			'whether to enable further optimizations to the blur. Recommended to leave on, as it will massively improve performance.',
	},
	{
		name: 'xray',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'if enabled, floating windows will ignore tiled windows in their blur. Only available if blur_new_optimizations is true. Will reduce overhead on floating  blur significantly.',
	},
	{
		name: 'noise',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.0117, 0, 1',
		description: 'how much noise to apply. [0.0 - 1.0]',
	},
	{
		name: 'contrast',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.8916, 0, 2',
		description: 'contrast modulation for blur. [0.0 - 2.0]',
	},
	{
		name: 'brightness',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.8172, 0, 2',
		description: 'brightness modulation for blur. [0.0 - 2.0]',
	},
	{
		name: 'vibrancy',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.1696, 0, 1',
		description: 'Increase saturation of blurred colors. [0.0 - 1.0]',
	},
	{
		name: 'vibrancy_darkness',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0, 0, 1',
		description: 'How strong the effect of vibrancy is on dark areas . [0.0 - 1.0]',
	},
	{
		name: 'special',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether to blur behind the special workspace (note: expensive)',
	},
	{
		name: 'popups',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether to blur popups (e.g. right-click menus)',
	},
	{
		name: 'popups_ignorealpha',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.2, 0, 1',
		description: 'works like ignorealpha in layer rules. If pixel opacity is below set value, will not blur. [0.0 - 1.0]',
	},
	{
		name: 'input_methods',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether to blur input methods (e.g. fcitx5)',
	},
	{
		name: 'input_methods_ignorealpha',
		path: 'decoration:blur',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.2, 0, 1',
		description: 'works like ignorealpha in layer rules. If pixel opacity is below set value, will not blur. [0.0 - 1.0]',
	},
	{
		name: 'enabled',
		path: 'animations',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'enable animations',
	},
	{
		name: 'workspace_wraparound',
		path: 'animations',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'changes the direction of slide animations between the first and last workspaces',
	},
	{
		name: 'kb_model',
		path: 'input',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: 'STRVAL_EMPTY',
		description: 'Appropriate XKB keymap parameter. See the note below.',
	},
	{
		name: 'kb_layout',
		path: 'input',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"us"',
		description: 'Appropriate XKB keymap parameter',
	},
	{
		name: 'kb_variant',
		path: 'input',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description: 'Appropriate XKB keymap parameter',
	},
	{
		name: 'kb_options',
		path: 'input',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description: 'Appropriate XKB keymap parameter',
	},
	{
		name: 'kb_rules',
		path: 'input',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description: 'Appropriate XKB keymap parameter',
	},
	{
		name: 'kb_file',
		path: 'input',
		type: 'CONFIG_OPTION_STRING_LONG',
		data: '""',
		description: 'Appropriate XKB keymap file',
	},
	{
		name: 'numlock_by_default',
		path: 'input',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Engage numlock by default.',
	},
	{
		name: 'resolve_binds_by_sym',
		path: 'input',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'Determines how keybinds act when multiple layouts are used. If false, keybinds will always act as if the first specified layout is active. If true,  keybinds specified by symbols are activated when you type the respective symbol with the current layout.',
	},
	{
		name: 'repeat_rate',
		path: 'input',
		type: 'CONFIG_OPTION_INT',
		data: '25, 0, 200',
		description: 'The repeat rate for held-down keys, in repeats per second.',
	},
	{
		name: 'repeat_delay',
		path: 'input',
		type: 'CONFIG_OPTION_INT',
		data: '600, 0, 2000',
		description: 'Delay before a held-down key is repeated, in milliseconds.',
	},
	{
		name: 'sensitivity',
		path: 'input',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0, -1, 1',
		description: 'Sets the mouse input sensitivity. Value is clamped to the range -1.0 to 1.0.',
	},
	{
		name: 'accel_profile',
		path: 'input',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description:
			"Sets the cursor acceleration profile. Can be one of adaptive, flat. Can also be custom, see below. Leave empty to use libinput's default mode for your  input device. [adaptive/flat/custom]",
	},
	{
		name: 'force_no_accel',
		path: 'input',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'Force no cursor acceleration. This bypasses most of your pointer settings to get as raw of a signal as possible. Enabling this is not recommended due to  potential cursor desynchronization.',
	},
	{
		name: 'rotation',
		path: 'input',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 359',
		description:
			'Sets the rotation of a device in degrees clockwise off the logical neutral position. Value is clamped to the range 0 to 359.',
	},
	{
		name: 'left_handed',
		path: 'input',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Switches RMB and LMB',
	},
	{
		name: 'scroll_points',
		path: 'input',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description:
			'Sets the scroll acceleration profile, when accel_profile is set to custom. Has to be in the form <step> <points>. Leave empty to have a flat scroll curve.',
	},
	{
		name: 'scroll_method',
		path: 'input',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description:
			'Sets the scroll method. Can be one of 2fg (2 fingers), edge, on_button_down, no_scroll. [2fg/edge/on_button_down/no_scroll]',
	},
	{
		name: 'scroll_button',
		path: 'input',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 300',
		description:
			'Sets the scroll button. Has to be an int, cannot be a string. Check wev if you have any doubts regarding the ID. 0 means default.',
	},
	{
		name: 'scroll_button_lock',
		path: 'input',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'If the scroll button lock is enabled, the button does not need to be held down. Pressing and releasing the button toggles the button lock, which logically  holds the button down or releases it. While the button is logically held down, motion events are converted to scroll events.',
	},
	{
		name: 'scroll_factor',
		path: 'input',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 0, 2',
		description:
			'Multiplier added to scroll movement for external mice. Note that there is a separate setting for touchpad scroll_factor.',
	},
	{
		name: 'natural_scroll',
		path: 'input',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Inverts scrolling direction. When enabled, scrolling moves content directly, rather than manipulating a scrollbar.',
	},
	{
		name: 'follow_mouse',
		path: 'input',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 3',
		description: 'Specify if and how cursor movement should affect window focus. See the note below. [0/1/2/3]',
	},
	{
		name: 'follow_mouse_threshold',
		path: 'input',
		type: 'CONFIG_OPTION_FLOAT',
		data: null,
		description:
			'The smallest distance in logical pixels the mouse needs to travel for the window under it to get focused. Works only with follow_mouse = 1.',
	},
	{
		name: 'focus_on_close',
		path: 'input',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "next,cursor"',
		description:
			'Controls the window focus behavior when a window is closed. When set to 0, focus will shift to the next window candidate. When set to 1, focus will shift  to the window under the cursor.',
	},
	{
		name: 'mouse_refocus',
		path: 'input',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description:
			"if disabled, mouse focus won't switch to the hovered window unless the mouse crosses a window boundary when follow_mouse=1.",
	},
	{
		name: 'float_switch_override_focus',
		path: 'input',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 2',
		description:
			'If enabled (1 or 2), focus will change to the window under the cursor when changing from tiled-to-floating and vice versa. If 2, focus will also follow  mouse on float-to-float switches.',
	},
	{
		name: 'special_fallthrough',
		path: 'input',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'if enabled, having only floating windows in the special workspace will not block focusing windows in the regular workspace.',
	},
	{
		name: 'off_window_axis_events',
		path: 'input',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 3',
		description:
			'Handles axis events around (gaps/border for tiled, dragarea/border for floated) a focused window. 0 ignores axis events 1 sends out-of-bound coordinates 2  fakes pointer coordinates to the closest point inside the window 3 warps the cursor to the closest point inside the window',
	},
	{
		name: 'emulate_discrete_scroll',
		path: 'input',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 2',
		description:
			'Emulates discrete scrolling from high resolution scrolling events. 0 disables it, 1 enables handling of non-standard events only, and 2 force enables all  scroll wheel events to be handled',
	},
	{
		name: 'disable_while_typing',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Disable the touchpad while typing.',
	},
	{
		name: 'natural_scroll',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Inverts scrolling direction. When enabled, scrolling moves content directly, rather than manipulating a scrollbar.',
	},
	{
		name: 'scroll_factor',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 0, 2',
		description: 'Multiplier applied to the amount of scroll movement.',
	},
	{
		name: 'middle_button_emulation',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			' Sending LMB and RMB simultaneously will be interpreted as a middle click. This disables any touchpad area that would normally send a middle click based on location.',
	},
	{
		name: 'tap_button_map',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description:
			'Sets the tap button mapping for touchpad button emulation. Can be one of lrm (default) or lmr (Left, Middle, Right Buttons). [lrm/lmr]',
	},
	{
		name: 'clickfinger_behavior',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			' Button presses with 1, 2, or 3 fingers will be mapped to LMB, RMB, and MMB respectively. This disables interpretation of clicks based on location on the touchpad.',
	},
	{
		name: 'tap-to-click',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Tapping on the touchpad with 1, 2, or 3 fingers will send LMB, RMB, and MMB respectively.',
	},
	{
		name: 'drag_lock',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 2',
		description:
			'When enabled, lifting the finger off while dragging will not drop the dragged item. 0 -> disabled, 1 -> enabled with timeout, 2 -> enabled sticky. dragging will not drop the dragged item.',
	},
	{
		name: 'tap-and-drag',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Sets the tap and drag mode for the touchpad',
	},
	{
		name: 'flip_x',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Inverts the horizontal movement of the touchpad',
	},
	{
		name: 'flip_y',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Inverts the vertical movement of the touchpad',
	},
	{
		name: 'drag_3fg',
		path: 'input:touchpad',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 2',
		description: 'Three Finger Drag 0 -> disabled, 1 -> 3 finger, 2 -> 4 finger',
	},
	{
		name: 'transform',
		path: 'input:touchdevice',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 6',
		description: 'Transform the input from touchdevices. The possible transformations are the same as those of the monitors',
	},
	{
		name: 'output',
		path: 'input:touchdevice',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description:
			'The monitor to bind touch devices. The default is auto-detection. To stop auto-detection, use an empty string or the [[Empty]] value.',
	},
	{
		name: 'enabled',
		path: 'input:touchdevice',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Whether input is enabled for touch devices.',
	},
	{
		name: 'share_states',
		path: 'input:virtualkeyboard',
		type: 'CONFIG_OPTION_INT',
		data: '2, 0, 2',
		description: 'Unify key down states and modifier states with other keyboards. 0 -> no, 1 -> yes, 2 -> yes unless IME client',
	},
	{
		name: 'release_pressed_on_close',
		path: 'input:virtualkeyboard',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Release all pressed keys by virtual keyboard on close.',
	},
	{
		name: 'transform',
		path: 'input:tablet',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 6',
		description: 'transform the input from tablets. The possible transformations are the same as those of the monitors',
	},
	{
		name: 'output',
		path: 'input:tablet',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description: 'the monitor to bind tablets. Can be current or a monitor name. Leave empty to map across all monitors.',
	},
	{
		name: 'region_position',
		path: 'input:tablet',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{}, {-20000, -20000}, {20000, 20000}',
		description:
			'position of the mapped region in monitor layout relative to the top left corner of the bound monitor or all monitors.',
	},
	{
		name: 'absolute_region_position',
		path: 'input:tablet',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether to treat the region_position as an absolute position in monitor layout. Only applies when output is empty.',
	},
	{
		name: 'region_size',
		path: 'input:tablet',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{}, {-100, -100}, {4000, 4000}',
		description:
			'size of the mapped region. When this variable is set, tablet input will be mapped to the region. [0, 0] or invalid size means unset.',
	},
	{
		name: 'relative_input',
		path: 'input:tablet',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether the input should be relative',
	},
	{
		name: 'left_handed',
		path: 'input:tablet',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if enabled, the tablet will be rotated 180 degrees',
	},
	{
		name: 'active_area_size',
		path: 'input:tablet',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{}, {}, {500, 500}',
		description: "size of tablet's active area in mm",
	},
	{
		name: 'active_area_position',
		path: 'input:tablet',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{}, {}, {500, 500}',
		description: 'position of the active area in mm',
	},
	{
		name: 'workspace_swipe_distance',
		path: 'gestures',
		type: 'CONFIG_OPTION_INT',
		data: '300, 0, 2000',
		description: 'in px, the distance of the touchpad gesture',
	},
	{
		name: 'workspace_swipe_touch',
		path: 'gestures',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enable workspace swiping from the edge of a touchscreen',
	},
	{
		name: 'workspace_swipe_invert',
		path: 'gestures',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'invert the direction (touchpad only)',
	},
	{
		name: 'workspace_swipe_touch_invert',
		path: 'gestures',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'invert the direction (touchscreen only)',
	},
	{
		name: 'workspace_swipe_min_speed_to_force',
		path: 'gestures',
		type: 'CONFIG_OPTION_INT',
		data: '30, 0, 200',
		description:
			'minimum speed in px per timepoint to force the change ignoring cancel_ratio. Setting to 0 will disable this mechanic.',
	},
	{
		name: 'workspace_swipe_cancel_ratio',
		path: 'gestures',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.5, 0, 1',
		description:
			'how much the swipe has to proceed in order to commence it. (0.7 -> if > 0.7 * distance, switch, if less, revert) [0.0 - 1.0]',
	},
	{
		name: 'workspace_swipe_create_new',
		path: 'gestures',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether a swipe right on the last workspace should create a new one.',
	},
	{
		name: 'workspace_swipe_direction_lock',
		path: 'gestures',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'if enabled, switching direction will be locked when you swipe past the direction_lock_threshold (touchpad only).',
	},
	{
		name: 'workspace_swipe_direction_lock_threshold',
		path: 'gestures',
		type: 'CONFIG_OPTION_INT',
		data: '10, 0, 200',
		description: 'in px, the distance to swipe before direction lock activates (touchpad only).',
	},
	{
		name: 'workspace_swipe_forever',
		path: 'gestures',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if enabled, swiping will not clamp at the neighboring workspaces but continue to the further ones.',
	},
	{
		name: 'workspace_swipe_use_r',
		path: 'gestures',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if enabled, swiping will use the r prefix instead of the m prefix for finding workspaces.',
	},
	{
		name: 'close_max_timeout',
		path: 'gestures',
		type: 'CONFIG_OPTION_INT',
		data: '1000, 10, 2000',
		description: 'Timeout for closing windows with the close gesture, in ms.',
	},
	{
		name: 'insert_after_current',
		path: 'group',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether new windows in a group spawn after current or at group tail',
	},
	{
		name: 'focus_removed_window',
		path: 'group',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether Hyprland should focus on the window that has just been moved out of the group',
	},
	{
		name: 'merge_groups_on_drag',
		path: 'group',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether window groups can be dragged into other groups',
	},
	{
		name: 'merge_groups_on_groupbar',
		path: 'group',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether one group will be merged with another when dragged into its groupbar',
	},
	{
		name: 'col.border_active',
		path: 'group',
		type: 'CONFIG_OPTION_GRADIENT',
		data: '"0x66ffff00"',
		description: 'border color for inactive windows',
	},
	{
		name: 'col.border_inactive',
		path: 'group',
		type: 'CONFIG_OPTION_GRADIENT',
		data: '"0x66777700"',
		description: 'border color for the active window',
	},
	{
		name: 'col.border_locked_inactive',
		path: 'group',
		type: 'CONFIG_OPTION_GRADIENT',
		data: '"0x66ff5500"',
		description: 'inactive border color for window that cannot be added to a group (see denywindowfromgroup dispatcher)',
	},
	{
		name: 'col.border_locked_active',
		path: 'group',
		type: 'CONFIG_OPTION_GRADIENT',
		data: '"0x66775500"',
		description: 'active border color for window that cannot be added to a group',
	},
	{
		name: 'auto_group',
		path: 'group',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'automatically group new windows',
	},
	{
		name: 'drag_into_group',
		path: 'group',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "disabled,enabled,only when dragging into the groupbar"',
		description:
			'whether dragging a window into a unlocked group will merge them. Options: 0 (disabled), 1 (enabled), 2 (only when dragging into the groupbar)',
	},
	{
		name: 'merge_floated_into_tiled_on_groupbar',
		path: 'group',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether dragging a floating window into a tiled window groupbar will merge them',
	},
	{
		name: 'group_on_movetoworkspace',
		path: 'group',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: "whether using movetoworkspace[silent] will merge the window into the workspace's solitary unlocked group",
	},
	{
		name: 'enabled',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'enables groupbars',
	},
	{
		name: 'font_family',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: 'STRVAL_EMPTY',
		description: 'font used to display groupbar titles, use misc:font_family if not specified',
	},
	{
		name: 'font_weight_active',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"normal"',
		description: 'weight of the font used to display active groupbar titles',
	},
	{
		name: 'font_weight_inactive',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"normal"',
		description: 'weight of the font used to display inactive groupbar titles',
	},
	{
		name: 'font_size',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_INT',
		data: '8, 2, 64',
		description: 'font size of groupbar title',
	},
	{
		name: 'gradients',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enables gradients',
	},
	{
		name: 'height',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_INT',
		data: '14, 1, 64',
		description: 'height of the groupbar',
	},
	{
		name: 'indicator_gap',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 64',
		description: 'height of the gap between the groupbar indicator and title',
	},
	{
		name: 'indicator_height',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_INT',
		data: '3, 1, 64',
		description: 'height of the groupbar indicator',
	},
	{
		name: 'stacked',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'render the groupbar as a vertical stack',
	},
	{
		name: 'priority',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_INT',
		data: '3, 0, 6',
		description: 'sets the decoration priority for groupbars',
	},
	{
		name: 'render_titles',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether to render titles in the group bar decoration',
	},
	{
		name: 'scrolling',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether scrolling in the groupbar changes group active window',
	},
	{
		name: 'rounding',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 20',
		description: 'how much to round the groupbar',
	},
	{
		name: 'rounding_power',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_FLOAT',
		data: '2, 2, 10',
		description: 'rounding power of groupbar corners (2 is a circle)',
	},
	{
		name: 'gradient_rounding',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 20',
		description: 'how much to round the groupbar gradient',
	},
	{
		name: 'gradient_rounding_power',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_FLOAT',
		data: '2, 2, 10',
		description: 'rounding power of groupbar gradient corners (2 is a circle)',
	},
	{
		name: 'round_only_edges',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'if yes, will only round at the groupbar edges',
	},
	{
		name: 'gradient_round_only_edges',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'if yes, will only round at the groupbar gradient edges',
	},
	{
		name: 'text_color',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_COLOR',
		data: '0xffffffff',
		description: 'color for window titles in the groupbar',
	},
	{
		name: 'text_color_inactive',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_COLOR',
		data: null,
		description: "color for inactive windows' titles in the groupbar (if unset, defaults to text_color)",
	},
	{
		name: 'text_color_locked_active',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_COLOR',
		data: null,
		description: "color for the active window's title in a locked group (if unset, defaults to text_color)",
	},
	{
		name: 'text_color_locked_inactive',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_COLOR',
		data: null,
		description: "color for inactive windows' titles in locked groups (if unset, defaults to text_color_inactive)",
	},
	{
		name: 'col.active',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_COLOR',
		data: '0x66ffff00',
		description: 'active group border color',
	},
	{
		name: 'col.inactive',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_COLOR',
		data: '0x66777700',
		description: 'inactive (out of focus) group border color',
	},
	{
		name: 'col.locked_active',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_COLOR',
		data: '0x66ff5500',
		description: 'active locked group border color',
	},
	{
		name: 'col.locked_inactive',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_COLOR',
		data: '0x66775500',
		description: 'controls the group bar text color',
	},
	{
		name: 'gaps_out',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_INT',
		data: '2, 0, 20',
		description: 'gap between gradients and window',
	},
	{
		name: 'gaps_in',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_INT',
		data: '2, 0, 20',
		description: 'gap between gradients',
	},
	{
		name: 'keep_upper_gap',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'keep an upper gap above gradient',
	},
	{
		name: 'text_offset',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: '0, -20, 20',
		description: 'set an offset for a text',
	},
	{
		name: 'text_padding',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: '0, 0, 22',
		description: 'set horizontal padding for a text',
	},
	{
		name: 'blur',
		path: 'group:groupbar',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enable background blur for groupbars',
	},
	{
		name: 'disable_hyprland_logo',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'disables the random Hyprland logo / anime girl background. :(',
	},
	{
		name: 'disable_splash_rendering',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'disables the Hyprland splash rendering. (requires a monitor reload to take effect)',
	},
	{
		name: 'col.splash',
		path: 'misc',
		type: 'CONFIG_OPTION_COLOR',
		data: '0xffffffff',
		description: 'Changes the color of the splash text (requires a monitor reload to take effect).',
	},
	{
		name: 'font_family',
		path: 'misc',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"Sans"',
		description:
			'Set the global default font to render the text including debug fps/notification, config error messages and etc., selected from system fonts.',
	},
	{
		name: 'splash_font_family',
		path: 'misc',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: 'STRVAL_EMPTY',
		description:
			'Changes the font used to render the splash text, selected from system fonts (requires a monitor reload to take effect).',
	},
	{
		name: 'force_default_wallpaper',
		path: 'misc',
		type: 'CONFIG_OPTION_INT',
		data: '-1, -1, 2',
		description:
			'Enforce any of the 3 default wallpapers. Setting this to 0 or 1 disables the anime background. -1 means “random”. [-1/0/1/2]',
	},
	{
		name: 'vfr',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'controls the VFR status of Hyprland. Heavily recommended to leave enabled to conserve resources.',
	},
	{
		name: 'vrr',
		path: 'misc',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 3',
		description:
			'\tcontrols the VRR (Adaptive Sync) of your monitors. 0 - off, 1 - on, 2 - fullscreen only, 3 - fullscreen with game or video content type [0/1/2/3]',
	},
	{
		name: 'mouse_move_enables_dpms',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'If DPMS is set to off, wake up the monitors if the mouse move',
	},
	{
		name: 'key_press_enables_dpms',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'If DPMS is set to off, wake up the monitors if a key is pressed.',
	},
	{
		name: 'name_vk_after_proc',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description:
			'Name virtual keyboards after the processes that create them. E.g. /usr/bin/fcitx5 will have hl-virtual-keyboard-fcitx5.',
	},
	{
		name: 'always_follow_on_dnd',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description:
			'Will make mouse focus follow the mouse when drag and dropping. Recommended to leave it enabled, especially for people using focus follows mouse at 0.',
	},
	{
		name: 'layers_hog_keyboard_focus',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'If true, will make keyboard-interactive layers keep their focus on mouse move (e.g. wofi, bemenu)',
	},
	{
		name: 'animate_manual_resizes',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'If true, will animate manual window resizes/moves',
	},
	{
		name: 'animate_mouse_windowdragging',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'If true, will animate windows being dragged by mouse, note that this can cause weird behavior on some curves',
	},
	{
		name: 'disable_autoreload',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'If true, the config will not reload automatically on save, and instead needs to be reloaded with hyprctl reload. Might save on battery.',
	},
	{
		name: 'enable_swallow',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Enable window swallowing',
	},
	{
		name: 'swallow_regex',
		path: 'misc',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description:
			' The class regex to be used for windows that should be swallowed (usually, a terminal). To know more about the list of regex which can be used use this cheatsheet.',
	},
	{
		name: 'swallow_exception_regex',
		path: 'misc',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description:
			'The title regex to be used for windows that should not be swallowed by the windows specified in swallow_regex (e.g. wev). The regex is matched against the  parent (e.g. Kitty) window’s title on the assumption that it changes to whatever process it’s running.',
	},
	{
		name: 'focus_on_activate',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Whether Hyprland should focus an app that requests to be focused (an activate request)',
	},
	{
		name: 'mouse_move_focuses_monitor',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Whether mouse moving into a different monitor should focus it',
	},
	{
		name: 'allow_session_lock_restore',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if true, will allow you to restart a lockscreen app in case it crashes (red screen of death)',
	},
	{
		name: 'session_lock_xray',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'keep rendering workspaces below your lockscreen',
	},
	{
		name: 'background_color',
		path: 'misc',
		type: 'CONFIG_OPTION_COLOR',
		data: '0x111111',
		description: 'change the background color. (requires enabled disable_hyprland_logo)',
	},
	{
		name: 'close_special_on_empty',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'close the special workspace if the last window is removed',
	},
	{
		name: 'on_focus_under_fullscreen',
		path: 'misc',
		type: 'CONFIG_OPTION_INT',
		data: '2, 0, 2',
		description:
			'if there is a fullscreen or maximized window, decide whether a tiled window requested to focus should replace it, stay behind or disable the  fullscreen/maximized state. 0 - ignore focus request (keep focus on fullscreen window), 1 - takes over, 2 - unfullscreen/unmaximize [0/1/2]',
	},
	{
		name: 'exit_window_retains_fullscreen',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if true, closing a fullscreen window makes the next focused window fullscreen',
	},
	{
		name: 'initial_workspace_tracking',
		path: 'misc',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 2',
		description:
			'if enabled, windows will open on the workspace they were invoked on. 0 - disabled, 1 - single-shot, 2 - persistent (all children too)',
	},
	{
		name: 'middle_click_paste',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether to enable middle-click-paste (aka primary selection)',
	},
	{
		name: 'render_unfocused_fps',
		path: 'misc',
		type: 'CONFIG_OPTION_INT',
		data: '15, 1, 120',
		description: "the maximum limit for renderunfocused windows' fps in the background",
	},
	{
		name: 'disable_xdg_env_checks',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'disable the warning if XDG environment is externally managed',
	},
	{
		name: 'disable_hyprland_guiutils_check',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'disable the warning if hyprland-guiutils is missing',
	},
	{
		name: 'disable_watchdog_warning',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether to disable the warning about not using start-hyprland.',
	},
	{
		name: 'lockdead_screen_delay',
		path: 'misc',
		type: 'CONFIG_OPTION_INT',
		data: '1000, 0, 5000',
		description: 'the delay in ms after the lockdead screen appears if the lock screen did not appear after a lock event occurred.',
	},
	{
		name: 'enable_anr_dialog',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether to enable the ANR (app not responding) dialog when your apps hang',
	},
	{
		name: 'anr_missed_pings',
		path: 'misc',
		type: 'CONFIG_OPTION_INT',
		data: '5, 1, 20',
		description: 'number of missed pings before showing the ANR dialog',
	},
	{
		name: 'screencopy_force_8b',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: "forces 8 bit screencopy (fixes apps that don't understand 10bit)",
	},
	{
		name: 'disable_scale_notification',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'disables notification popup when a monitor fails to set a suitable scale and falls back to suggested',
	},
	{
		name: 'size_limits_tiled',
		path: 'misc',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether to apply minsize and maxsize rules to tiled windows',
	},
	{
		name: 'pass_mouse_when_bound',
		path: 'binds',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if disabled, will not pass the mouse events to apps / dragging windows around if a keybind has been triggered.',
	},
	{
		name: 'scroll_event_delay',
		path: 'binds',
		type: 'CONFIG_OPTION_INT',
		data: '300, 0, 2000',
		description: 'in ms, how many ms to wait after a scroll event to allow passing another one for the binds.',
	},
	{
		name: 'workspace_back_and_forth',
		path: 'binds',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'If enabled, an attempt to switch to the currently focused workspace will instead switch to the previous workspace. Akin to i3’s auto_back_and_forth.',
	},
	{
		name: 'hide_special_on_workspace_change',
		path: 'binds',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'If enabled, changing the active workspace (including to itself) will hide the special workspace on the monitor where the newly active workspace resides.',
	},
	{
		name: 'allow_workspace_cycles',
		path: 'binds',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'If enabled, workspaces don’t forget their previous workspace, so cycles can be created by switching to the first workspace in a sequence, then endlessly  going to the previous workspace.',
	},
	{
		name: 'workspace_center_on',
		path: 'binds',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 1',
		description:
			'Whether switching workspaces should center the cursor on the workspace (0) or on the last active window for that workspace (1)',
	},
	{
		name: 'focus_preferred_method',
		path: 'binds',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 1',
		description:
			'sets the preferred focus finding method when using focuswindow/movewindow/etc with a direction. 0 - history (recent have priority), 1 - length (longer  shared edges have priority)',
	},
	{
		name: 'ignore_group_lock',
		path: 'binds',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'If enabled, dispatchers like moveintogroup, moveoutofgroup and movewindoworgroup will ignore lock per group.',
	},
	{
		name: 'movefocus_cycles_fullscreen',
		path: 'binds',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'If enabled, when on a fullscreen window, movefocus will cycle fullscreen, if not, it will move the focus in a direction.',
	},
	{
		name: 'movefocus_cycles_groupfirst',
		path: 'binds',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			"If enabled, when in a grouped window, movefocus will cycle windows in the groups first, then at each ends of tabs, it'll move on to other windows/groups",
	},
	{
		name: 'disable_keybind_grabbing',
		path: 'binds',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'If enabled, apps that request keybinds to be disabled (e.g. VMs) will not be able to do so.',
	},
	{
		name: 'window_direction_monitor_fallback',
		path: 'binds',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description:
			'If enabled, moving a window or focus over the edge of a monitor with a direction will move it to the next monitor in that direction.',
	},
	{
		name: 'allow_pin_fullscreen',
		path: 'binds',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Allows fullscreen to pinned windows, and restore their pinned status afterwards',
	},
	{
		name: 'drag_threshold',
		path: 'binds',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, INT_MAX',
		description: 'Movement threshold in pixels for window dragging and c/g bind flags. 0 to disable and grab on mousedown.',
	},
	{
		name: 'enabled',
		path: 'xwayland',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'allow running applications using X11',
	},
	{
		name: 'use_nearest_neighbor',
		path: 'xwayland',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'uses the nearest neighbor filtering for xwayland apps, making them pixelated rather than blurry',
	},
	{
		name: 'force_zero_scaling',
		path: 'xwayland',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'forces a scale of 1 on xwayland windows on scaled displays.',
	},
	{
		name: 'create_abstract_socket',
		path: 'xwayland',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Create the abstract Unix domain socket for XWayland',
	},
	{
		name: 'nvidia_anti_flicker',
		path: 'opengl',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description:
			'reduces flickering on nvidia at the cost of possible frame drops on lower-end GPUs. On non-nvidia, this is ignored.',
	},
	{
		name: 'direct_scanout',
		path: 'render',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 2',
		description:
			"Enables direct scanout. Direct scanout attempts to reduce lag when there is only one fullscreen application on a screen (e.g. game). It is also  recommended to set this to false if the fullscreen application shows graphical glitches. 0 - off, 1 - on, 2 - auto (on with content type 'game')",
	},
	{
		name: 'expand_undersized_textures',
		path: 'render',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Whether to expand textures that have not yet resized to be larger, or to just stretch them instead.',
	},
	{
		name: 'xp_mode',
		path: 'render',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Disable back buffer and bottom layer rendering.',
	},
	{
		name: 'ctm_animation',
		path: 'render',
		type: 'CONFIG_OPTION_INT',
		data: '2, 0, 2',
		description: "Whether to enable a fade animation for CTM changes (hyprsunset). 2 means 'auto' (Yes on everything but Nvidia).",
	},
	{
		name: 'cm_fs_passthrough',
		path: 'render',
		type: 'CONFIG_OPTION_INT',
		data: '2, 0, 2',
		description: 'Passthrough color settings for fullscreen apps when possible',
	},
	{
		name: 'cm_enabled',
		path: 'render',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Enable Color Management pipelines (requires restart to fully take effect)',
	},
	{
		name: 'send_content_type',
		path: 'render',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Report content type to allow monitor profile autoswitch (may result in a black screen during the switch)',
	},
	{
		name: 'cm_auto_hdr',
		path: 'render',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 2',
		description:
			'Auto-switch to hdr mode when fullscreen app is in hdr, 0 - off, 1 - hdr, 2 - hdredid (cm_fs_passthrough can switch to hdr even when this setting is off)',
	},
	{
		name: 'new_render_scheduling',
		path: 'render',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'enable new render scheduling, which should improve FPS on underpowered devices. This does not add latency when your PC can keep up.',
	},
	{
		name: 'non_shader_cm',
		path: 'render',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "disable,always,ondemand,ignore"',
		description:
			'Enable CM without shader. 0 - disable, 1 - whenever possible, 2 - DS and passthrough only, 3 - disable and ignore CM issues',
	},
	{
		name: 'cm_sdr_eotf',
		path: 'render',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "default,gamma22,gamma22force,srgb"',
		description:
			'Default transfer function for displaying SDR apps. 0 - Use default value (Gamma 2.2), 1 - Treat unspecified as Gamma 2.2, 2 - Treat  unspecified and sRGB as Gamma 2.2, 3 - Treat unspecified as sRGB',
	},
	{
		name: 'invisible',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: "don't render cursors",
	},
	{
		name: 'no_hardware_cursors',
		path: 'cursor',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "Disabled,Enabled,Auto"',
		description: 'disables hardware cursors. Auto = disable when multi-gpu on nvidia',
	},
	{
		name: 'no_break_fs_vrr',
		path: 'cursor',
		type: 'CONFIG_OPTION_INT',
		data: '2, 0, 2',
		description:
			"disables scheduling new frames on cursor movement for fullscreen apps with VRR enabled to avoid framerate spikes (may require no_hardware_cursors = true)  0 - off, 1 - on, 2 - auto (on with content type 'game')",
	},
	{
		name: 'min_refresh_rate',
		path: 'cursor',
		type: 'CONFIG_OPTION_INT',
		data: '24, 10, 500',
		description:
			'minimum refresh rate for cursor movement when no_break_fs_vrr is active. Set to minimum supported refresh rate or higher',
	},
	{
		name: 'hotspot_padding',
		path: 'cursor',
		type: 'CONFIG_OPTION_INT',
		data: '1, 0, 20',
		description: 'the padding, in logical px, between screen edges and the cursor',
	},
	{
		name: 'inactive_timeout',
		path: 'cursor',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 20',
		description: 'in seconds, after how many seconds of cursor’s inactivity to hide it. Set to 0 for never.',
	},
	{
		name: 'no_warps',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if true, will not warp the cursor in many cases (focusing, keybinds, etc)',
	},
	{
		name: 'persistent_warps',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'When a window is refocused, the cursor returns to its last position relative to that window, rather than to the centre.',
	},
	{
		name: 'warp_on_change_workspace',
		path: 'cursor',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "Disabled,Enabled,Force"',
		description:
			'Move the cursor to the last focused window after changing the workspace. Options: 0 (Disabled), 1 (Enabled), 2 (Force - ignores cursor:no_warps option)',
	},
	{
		name: 'warp_on_toggle_special',
		path: 'cursor',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "Disabled,Enabled,Force"',
		description:
			'Move the cursor to the last focused window when toggling a special workspace. Options: 0 (Disabled), 1 (Enabled),  2 (Force - ignores cursor:no_warps option)',
	},
	{
		name: 'default_monitor',
		path: 'cursor',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '""',
		description: 'the name of a default monitor for the cursor to be set to on startup (see hyprctl monitors for names)',
	},
	{
		name: 'zoom_factor',
		path: 'cursor',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 1, 10',
		description: 'the factor to zoom by around the cursor. Like a magnifying glass. Minimum 1.0 (meaning no zoom)',
	},
	{
		name: 'zoom_rigid',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether the zoom should follow the cursor rigidly (cursor is always centered if it can be) or loosely',
	},
	{
		name: 'zoom_disable_aa',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'If enabled, when zooming, no antialiasing will be used (zoom will be pixelated)',
	},
	{
		name: 'zoom_detached_camera',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Detaches the camera from the mouse when zoomed in, only ever moving to keep the mouse in view',
	},
	{
		name: 'enable_hyprcursor',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether to enable hyprcursor support',
	},
	{
		name: 'hide_on_key_press',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Hides the cursor when you press any key until the mouse is moved.',
	},
	{
		name: 'hide_on_touch',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Hides the cursor when the last input was a touch input until a mouse input is done.',
	},
	{
		name: 'hide_on_tablet',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Hides the cursor when the last input was a tablet input until a mouse input is done.',
	},
	{
		name: 'use_cpu_buffer',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Makes HW cursors use a CPU buffer. Required on Nvidia to have HW cursors. Experimental',
	},
	{
		name: 'sync_gsettings_theme',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description:
			'sync xcursor theme with gsettings, it applies cursor-theme and cursor-size on theme load to gsettings making most CSD gtk based clients use same xcursor  theme and size.',
	},
	{
		name: 'warp_back_after_non_mouse_input',
		path: 'cursor',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'warp the cursor back to where it was after using a non-mouse input to move it, and then returning back to mouse.',
	},
	{
		name: 'no_update_news',
		path: 'ecosystem',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'disable the popup that shows up when you update hyprland to a new version.',
	},
	{
		name: 'no_donation_nag',
		path: 'ecosystem',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'disable the popup that shows up twice a year encouraging to donate.',
	},
	{
		name: 'enforce_permissions',
		path: 'ecosystem',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether to enable permission control (see https://wiki.hypr.land/Configuring/Permissions/).',
	},
	{
		name: 'overlay',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'print the debug performance overlay. Disable VFR for accurate results.',
	},
	{
		name: 'damage_blink',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'disable logging to a file',
	},
	{
		name: 'disable_logs',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'disable logging to a file',
	},
	{
		name: 'disable_time',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'disables time logging',
	},
	{
		name: 'damage_tracking',
		path: 'debug',
		type: 'CONFIG_OPTION_INT',
		data: '2, 0, 2',
		description: 'redraw only the needed bits of the display. Do not change. (default: full - 2) monitor - 1, none - 0',
	},
	{
		name: 'enable_stdout_logs',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enables logging to stdout',
	},
	{
		name: 'manual_crash',
		path: 'debug',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 1',
		description: 'set to 1 and then back to 0 to crash Hyprland.',
	},
	{
		name: 'suppress_errors',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if true, do not display config file parsing errors.',
	},
	{
		name: 'disable_scale_checks',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'disables verification of the scale factors. Will result in pixel alignment and rounding errors.',
	},
	{
		name: 'error_limit',
		path: 'debug',
		type: 'CONFIG_OPTION_INT',
		data: '5, 0, 20',
		description: 'limits the number of displayed config file parsing errors.',
	},
	{
		name: 'error_position',
		path: 'debug',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 1',
		description: 'sets the position of the error bar. top - 0, bottom - 1',
	},
	{
		name: 'colored_stdout_logs',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'enables colors in the stdout logs.',
	},
	{
		name: 'log_damage',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enables logging the damage.',
	},
	{
		name: 'pass',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enables render pass debugging.',
	},
	{
		name: 'full_cm_proto',
		path: 'debug',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'claims support for all cm proto features (requires restart)',
	},
	{
		name: 'pseudotile',
		path: 'dwindle',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enable pseudotiling. Pseudotiled windows retain their floating size when tiled.',
	},
	{
		name: 'force_split',
		path: 'dwindle',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "follow mouse,left or top,right or bottom"',
		description:
			'0 -> split follows mouse, 1 -> always split to the left (new = left or top) 2 -> always split to the right (new = right or bottom)',
	},
	{
		name: 'preserve_split',
		path: 'dwindle',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if enabled, the split (side/top) will not change regardless of what happens to the container.',
	},
	{
		name: 'smart_split',
		path: 'dwindle',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			"if enabled, allows a more precise control over the window split direction based on the cursor's position. The window is conceptually divided into four  triangles, and cursor's triangle determines the split direction. This feature also turns on preserve_split.",
	},
	{
		name: 'smart_resizing',
		path: 'dwindle',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description:
			" if enabled, resizing direction will be determined by the mouse's position on the window (nearest to which corner). Else, it is based on the window's tiling position.",
	},
	{
		name: 'permanent_direction_override',
		path: 'dwindle',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description:
			'if enabled, makes the preselect direction persist until either this mode is turned off, another direction is specified, or a non-direction is specified  (anything other than l,r,u/t,d/b)',
	},
	{
		name: 'special_scale_factor',
		path: 'dwindle',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 0, 1',
		description: 'specifies the scale factor of windows on the special workspace [0 - 1]',
	},
	{
		name: 'split_width_multiplier',
		path: 'dwindle',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 0.1, 3',
		description: 'specifies the auto-split width multiplier',
	},
	{
		name: 'use_active_for_splits',
		path: 'dwindle',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'whether to prefer the active window or the mouse position for splits',
	},
	{
		name: 'default_split_ratio',
		path: 'dwindle',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 0.1, 1.9',
		description: 'the default split ratio on window open. 1 means even 50/50 split. [0.1 - 1.9]',
	},
	{
		name: 'split_bias',
		path: 'dwindle',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "directional,current"',
		description:
			'specifies which window will receive the split ratio. 0 -> directional (the top or left window), 1 -> the current window',
	},
	{
		name: 'precise_mouse_move',
		path: 'dwindle',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'if enabled, bindm movewindow will drop the window more precisely depending on where your mouse is.',
	},
	{
		name: 'single_window_aspect_ratio',
		path: 'dwindle',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{0, 0}, {0, 0}, {1000., 1000.}',
		description:
			'If specified, whenever only a single window is open, it will be coerced into the specified aspect ratio.  Ignored if the y-value is zero.',
	},
	{
		name: 'single_window_aspect_ratio_tolerance',
		path: 'dwindle',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.1f, 0.f, 1.f',
		description: "Minimum distance for single_window_aspect_ratio to take effect, in fractions of the monitor's size.",
	},
	{
		name: 'allow_small_split',
		path: 'master',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'enable adding additional master windows in a horizontal split style',
	},
	{
		name: 'special_scale_factor',
		path: 'master',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1, 0, 1',
		description: 'the scale of the special workspace windows. [0.0 - 1.0]',
	},
	{
		name: 'mfact',
		path: 'master',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.55, 0, 1',
		description:
			' the size as a percentage of the master window, for example `mfact = 0.70` would mean 70% of the screen will be the master window, and 30% the slave [0.0 - 1.0]',
	},
	{
		name: 'new_status',
		path: 'master',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"slave"',
		description:
			'`master`: new window becomes master; `slave`: new windows are added to slave stack; `inherit`: inherit from focused window',
	},
	{
		name: 'new_on_top',
		path: 'master',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether a newly open window should be on the top of the stack',
	},
	{
		name: 'new_on_active',
		path: 'master',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"none"',
		description:
			'`before`, `after`: place new window relative to the focused window; `none`: place new window according to the value of `new_on_top`. ',
	},
	{
		name: 'orientation',
		path: 'master',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: '"left"',
		description: 'default placement of the master area, can be left, right, top, bottom or center',
	},
	{
		name: 'slave_count_for_center_master',
		path: 'master',
		type: 'CONFIG_OPTION_INT',
		data: '2, 0, 10',
		description:
			'when using orientation=center, make the master window centered only when at least this many slave windows are open. (Set 0 to always_center_master)',
	},
	{
		name: 'center_ignores_reserved',
		path: 'master',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'centers the master window on monitor ignoring reserved areas',
	},
	{
		name: 'smart_resizing',
		path: 'master',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description:
			" if enabled, resizing direction will be determined by the mouse's position on the window (nearest to which corner). Else, it is based on the window's tiling position.",
	},
	{
		name: 'drop_at_cursor',
		path: 'master',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description:
			'when enabled, dragging and dropping windows will put them at the cursor position. Otherwise, when dropped at the stack side, they will go to the  top/bottom of the stack depending on new_on_top.',
	},
	{
		name: 'always_keep_position',
		path: 'master',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'whether to keep the master window in its configured position when there are no slave windows',
	},
	{
		name: 'prefer_hdr',
		path: 'quirks',
		type: 'CONFIG_OPTION_INT',
		data: '0, 0, 2',
		description: 'Prefer HDR mode. 0 - off, 1 - always, 2 - gamescope only',
	},

	// -------------------------
	// WindowRuleProps
	// -------------------------
	{
		name: 'match:class',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Windows with class matching RegEx.',
	},
	{
		name: 'match:title',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Windows with title matching RegEx.',
	},
	{
		name: 'match:initial_class',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Windows with initialClass matching RegEx.',
	},
	{
		name: 'match:initial_title',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Windows with initialTitle matching RegEx.',
	},
	{
		name: 'match:tag',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Windows with matching tag.',
	},
	{
		name: 'match:xwayland',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'XWayland windows.',
	},
	{
		name: 'match:float',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Floating windows.',
	},
	{
		name: 'match:fullscreen',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Fullscreen windows.',
	},
	{
		name: 'match:pin',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Pinned windows.',
	},
	{
		name: 'match:focus',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Currently focused window.',
	},
	{
		name: 'match:group',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Grouped windows.',
	},
	{
		name: 'match:modal',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Modal windows (e.g. “Are you sure” popups).',
	},
	{
		name: 'match:fullscreen_state_client',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,3',
		description: 'Windows with matching fullscreenstate sent to the client (0:none,1:maximize,2:fullscreen,3:both).',
	},
	{
		name: 'match:fullscreen_state_internal',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,3',
		description: 'Windows with matching internal fullscreenstate (0:none,1:maximize,2:fullscreen,3:both).',
	},
	{
		name: 'match:workspace',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Windows on matching workspace (id, name, or selector).',
	},
	{
		name: 'match:content',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,3',
		description: 'Windows with specified content type (none=0, photo=1, video=2, game=3).',
	},
	{
		name: 'match:xdg_tag',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Match a window by its xdgTag.',
	},

	// -------------------------
	// Static / Dynamic Effects
	// -------------------------
	{
		name: 'float',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Floats a window.',
	},
	{
		name: 'tile',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Tiles a window.',
	},
	{
		name: 'fullscreen',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Fullscreens a window.',
	},
	{
		name: 'maximize',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Maximizes a window.',
	},
	{
		name: 'fullscreen_state',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,3',
		description: 'Sets fullscreen mode (internal/client).',
	},
	{
		name: 'move',
		path: 'windowrule',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{0,0},{-9999,-9999},{9999,9999}',
		description: 'Moves a floating window to given coordinates.',
	},
	{
		name: 'size',
		path: 'windowrule',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{100,100},{1,1},{9999,9999}',
		description: 'Resizes a floating window.',
	},
	{
		name: 'center',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Centers a floating window on the monitor.',
	},
	{
		name: 'pseudo',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Pseudotiles a window.',
	},
	{
		name: 'monitor',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Sets the monitor for the window (id or name).',
	},
	{
		name: 'workspace',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Sets the workspace for the window.',
	},
	{
		name: 'no_initial_focus',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disables initial focus.',
	},
	{
		name: 'pin',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Pins the window to all workspaces (floating only).',
	},
	{
		name: 'suppress_event',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Ignores specific events (space-separated).',
	},
	{
		name: 'content',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Sets content type (none|photo|video|game).',
	},
	{
		name: 'no_close_for',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,60000',
		description: 'Window uncloseable for given ms.',
	},
	{
		name: 'border_color',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '""',
		description: 'Forces the border color (can include gradients).',
	},
	{
		name: 'opacity',
		path: 'windowrule',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1.0,0.0,1.0',
		description: 'Overall window opacity (can include active/inactive/fullscreen).',
	},
	{
		name: 'rounding',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,100',
		description: 'Window rounding in pixels.',
	},
	{
		name: 'rounding_power',
		path: 'windowrule',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1.0,0.1,5.0',
		description: 'Overrides the rounding power.',
	},
	{
		name: 'allows_input',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Force window to receive input (XWayland).',
	},
	{
		name: 'dim_around',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Dims everything around the window.',
	},
	{
		name: 'decorate',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Whether to draw window decorations.',
	},
	{
		name: 'focus_on_activate',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Focus app that requests it.',
	},
	{
		name: 'keep_aspect_ratio',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Force aspect ratio when resizing.',
	},
	{
		name: 'nearest_neighbor',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Use nearest neighbor filtering.',
	},
	{
		name: 'no_anim',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disable animations for the window.',
	},
	{
		name: 'no_blur',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disable blur for the window.',
	},
	{
		name: 'no_dim',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disable window dimming.',
	},
	{
		name: 'no_focus',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disable focus to the window.',
	},
	{
		name: 'no_follow_mouse',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Prevent focus when mouse moves over the window.',
	},
	{
		name: 'no_shadow',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disable shadows.',
	},
	{
		name: 'no_shortcuts_inhibit',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disallow app from inhibiting shortcuts.',
	},
	{
		name: 'no_screen_share',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Hide window from screen sharing.',
	},
	{
		name: 'opaque',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Force window to be opaque.',
	},
	{
		name: 'force_rgbx',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Ignore alpha channel on the window.',
	},
	{
		name: 'sync_fullscreen',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Sync fullscreen mode with the window.',
	},
	{
		name: 'immediate',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Force tearing to allow immediate updates.',
	},
	{
		name: 'xray',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Enable blur xray mode.',
	},
	{
		name: 'render_unfocused',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Render window even if not visible.',
	},
	{
		name: 'scroll_mouse',
		path: 'windowrule',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1.0,0.0,10.0',
		description: 'Override mouse scroll factor.',
	},
	{
		name: 'scroll_touchpad',
		path: 'windowrule',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1.0,0.0,10.0',
		description: 'Override touchpad scroll factor.',
	},

	// -------------------------
	// Group Rules
	// -------------------------
	{
		name: 'group:set',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Open window as part of a group.',
	},
	{
		name: 'group:new',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Shorthand for barred set.',
	},
	{
		name: 'group:lock',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Lock the group that added this window.',
	},
	{
		name: 'group:barred',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Do not auto-group into focused unlocked group.',
	},
	{
		name: 'group:deny',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Do not allow window to be added to a group.',
	},
	{
		name: 'group:invade',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Force open window in locked group.',
	},
	{
		name: 'group:override',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Override other group rules.',
	},
	{
		name: 'group:unset',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Clear all group rules.',
	},
]

export function findConfigDescription(path, name) {
	let config_json = config_descriptions.find((item) => item.path === path && item.name === name)
	return config_json
}

export function findAdjacentConfigKeys(path, exclude = []) {
	let configKeys = config_descriptions.filter((item) => item.path === path).filter((item) => !exclude.includes(item.name))
	// console.table(configKeys)
	return configKeys
}

const windowruleSchema = []
