windowrule {
  match:title = zen
  match:class = ""
  no_initial_focus = true
} # come
bindr = SUPER, F1, toggle, floating

input {
  kb_layout = us
  kb_variant = intl
  repeat_delay = 300
  repeat_rate = 50
  kb_model = gb

  tablet {
    active_area_position = 1 1
    active_area_size = NaN NaN
  } 
} # hello