import shutil
import os.path
from pathlib import Path
from rich.console import Console

import sys

parent_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(parent_dir))

import helpers


console = Console()

dispatcher_wiki_content = ''
with open(f'{Path(__file__).resolve().parent.parent}/.hyprland-wiki/content/Configuring/Dispatchers.md', 'r') as file:
	dispatcher_wiki_content = file.readlines()

found_header: bool = False
table_started = False
table_ended = False
table_content = []

while not table_ended:
	for line in dispatcher_wiki_content:
		if line.strip().startswith('## List of Dispatchers'):
			found_header = True
			print(f'Found header {line}')
		if found_header and not table_started and line.strip().startswith('|'):
			table_started = True
		if found_header and line.strip().startswith('|'):
			table_content.append(line.strip('\n').strip().strip('|').strip())
		if table_started and not line.strip().startswith('|'):
			table_ended = True
			break

headers = [cell.strip().lower() for cell in table_content[0].split('|')]
contents = table_content[2:]
dataset = []
for line in contents:
	data_content = [cell.strip().strip() for cell in line.strip().split('|')]
	final_data = {}
	for i, header in enumerate(headers):
		final_data[header] = data_content[i]
	final_data['text'] = final_data['dispatcher']  # compatibility
	final_data['label'] = final_data['dispatcher']  # futureproofing
	final_data['value'] = final_data['dispatcher']  # futureproofing
	dataset.append(final_data)

version = helpers.get_wiki_version()

with open(f'{Path(__file__).resolve().parent}/dispatchers.ts', 'w+') as file:
	file.write('export const dispatchers = ')
	file.write(helpers.dumpjsobject(dataset))
	file.write(';')
	file.write('\n')
	file.write(f'// Autogenerated from wiki {version} using {os.path.basename(Path(__file__).resolve())}')

shutil.move(
	f'{Path(__file__).resolve().parent}/dispatchers.ts',
	f'{Path(__file__).parent.parent.parent / "src" / "ui-src" / "scripts" / "HyprlandSpecific" / "dispatchers.ts"}',
)
# console.print(Path(__file__).parent.parent.parent / 'src' / 'ui-src' / 'scripts' / 'HyprlandSpecific')

# console.print(JSON(json.dumps(dataset, indent=2)))
