import type { ConfigDescription } from '@scripts/types/configDescriptionTypes.ts'

export const NiriLayoutCDs: ConfigDescription[] = [
	// --- Root Layout Settings ---
	{ name: 'gaps', path: 'layout', type: 'CONFIG_OPTION_INT', data: '16, 0, 128', description: 'Gaps between windows and screen edges.' },
	{
		name: 'center-focused-column',
		path: 'layout',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "never,always,on-overflow"',
		description: 'Keep the focused column centered on the screen.',
	},
	{
		name: 'always-center-single-column',
		path: 'layout',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Always center the column if it is the only one on the workspace.',
	},
	{
		name: 'empty-workspace-above-first',
		path: 'layout',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Whether to create new workspaces above the first one.',
	},
	{
		name: 'default-column-display',
		path: 'layout',
		type: 'CONFIG_OPTION_CHOICE',
		data: '0, "tabbed,stacked"',
		description: 'Default display mode for windows within a column.',
	},
	{
		name: 'background-color',
		path: 'layout',
		type: 'CONFIG_OPTION_COLOR',
		data: '003300',
		description: 'Solid color for the background.',
	},

	// --- Column & Window Sizing ---
	{ name: 'preset-column-widths', path: 'layout', type: 'GROUP', data: '', description: 'Widths available for column resizing cycles.' },
	{
		name: 'proportion',
		path: 'layout:preset-column-widths',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.5, 0.1, 1.0',
		description: 'Column width as a proportion of the screen width.',
	},
	{ name: 'default-column-width', path: 'layout', type: 'GROUP', data: '', description: 'Starting width for new columns.' },
	{
		name: 'proportion',
		path: 'layout:default-column-width',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.5, 0.1, 1.0',
		description: 'Default width proportion for new columns.',
	},
	{
		name: 'preset-window-heights',
		path: 'layout',
		type: 'GROUP',
		data: '',
		description: 'Heights available for window resizing cycles.',
	},
	{
		name: 'proportion',
		path: 'layout:preset-window-heights',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.5, 0.1, 1.0',
		description: 'Window height as a proportion of the column height.',
	},

	// --- Focus Ring ---
	{ name: 'focus-ring', path: 'layout', type: 'GROUP', data: '', description: 'Highlight ring around the focused window.' },
	{
		name: 'on',
		path: 'layout:focus-ring',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Enable the focus ring.',
	},
	{
		name: 'off',
		path: 'layout:focus-ring',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Disable the focus ring.',
	},
	{ name: 'width', path: 'layout:focus-ring', type: 'CONFIG_OPTION_INT', data: '4, 1, 20', description: 'Thickness of the focus ring.' },
	{
		name: 'active-color',
		path: 'layout:focus-ring',
		type: 'CONFIG_OPTION_COLOR',
		data: '7fc8ff',
		description: 'Ring color for active windows.',
	},
	{
		name: 'inactive-color',
		path: 'layout:focus-ring',
		type: 'CONFIG_OPTION_COLOR',
		data: '505050',
		description: 'Ring color for inactive windows.',
	},
	{
		name: 'urgent-color',
		path: 'layout:focus-ring',
		type: 'CONFIG_OPTION_COLOR',
		data: '9b0000',
		description: 'Ring color for urgent windows.',
	},
	{
		name: 'active-gradient',
		path: 'layout:focus-ring',
		type: 'CONFIG_OPTION_GRADIENT',
		data: '',
		description: 'Gradient for the active focus ring.',
	},

	// --- Border ---
	{ name: 'border', path: 'layout', type: 'GROUP', data: '', description: 'Window border settings.' },
	{ name: 'on', path: 'layout:border', type: 'CONFIG_OPTION_FLAG', data: '', description: 'Enable window borders.' },
	{ name: 'off', path: 'layout:border', type: 'CONFIG_OPTION_FLAG', data: '', description: 'Disable window borders.' },
	{ name: 'width', path: 'layout:border', type: 'CONFIG_OPTION_INT', data: '4, 1, 20', description: 'Thickness of the window border.' },
	{
		name: 'active-color',
		path: 'layout:border',
		type: 'CONFIG_OPTION_COLOR',
		data: 'ffc87f',
		description: 'Border color for active windows.',
	},
	{
		name: 'inactive-color',
		path: 'layout:border',
		type: 'CONFIG_OPTION_COLOR',
		data: '505050',
		description: 'Border color for inactive windows.',
	},
	{
		name: 'urgent-color',
		path: 'layout:border',
		type: 'CONFIG_OPTION_COLOR',
		data: '9b0000',
		description: 'Border color for urgent windows.',
	},

	// --- Shadow ---
	{ name: 'shadow', path: 'layout', type: 'GROUP', data: '', description: 'Window drop shadow settings.' },
	{ name: 'on', path: 'layout:shadow', type: 'CONFIG_OPTION_FLAG', data: '', description: 'Enable window shadows.' },
	{ name: 'off', path: 'layout:shadow', type: 'CONFIG_OPTION_FLAG', data: '', description: 'Disable window shadows.' },
	{
		name: 'softness',
		path: 'layout:shadow',
		type: 'CONFIG_OPTION_INT',
		data: '30, 0, 100',
		description: 'Blur strength of the shadow.',
	},
	{ name: 'spread', path: 'layout:shadow', type: 'CONFIG_OPTION_INT', data: '5, 0, 50', description: 'Expansion of the shadow.' },
	{
		name: 'offset',
		path: 'layout:shadow',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{0, 5}, {-100, -100}, {100, 100}',
		description: 'X and Y offset of the shadow.',
	},
	{
		name: 'draw-behind-window',
		path: 'layout:shadow',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Whether to draw shadow parts that are behind the window.',
	},
	{ name: 'color', path: 'layout:shadow', type: 'CONFIG_OPTION_COLOR', data: '00000070', description: 'Shadow color with alpha.' },

	// --- Tab Indicator ---
	{ name: 'tab-indicator', path: 'layout', type: 'GROUP', data: '', description: 'Visual cues for tabbed window groups.' },
	{
		name: 'on',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Enable tab indicators.',
	},
	{
		name: 'off',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Disable tab indicators.',
	},
	{
		name: 'hide-when-single-tab',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Hide the indicator if only one window is in the column.',
	},
	{
		name: 'place-within-column',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Place the indicator inside the window frame.',
	},
	{
		name: 'gap',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_INT',
		data: '5, 0, 50',
		description: 'Gap between the indicator and the window edge.',
	},
	{
		name: 'width',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_INT',
		data: '4, 1, 20',
		description: 'Thickness of the tab indicator.',
	},
	{
		name: 'length',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1.0, 0.1, 1.0',
		description: 'Length of the indicator relative to window size.',
	},
	{
		name: 'position',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_CHOICE',
		data: '1, "left,right,top,bottom"',
		description: 'Side of the window where the indicator appears.',
	},
	{
		name: 'gaps-between-tabs',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_INT',
		data: '2, 0, 20',
		description: 'Space between individual tab indicators.',
	},
	{
		name: 'corner-radius',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_INT',
		data: '8, 0, 20',
		description: 'Rounding of indicator corners.',
	},
	{
		name: 'active-color',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_COLOR',
		data: 'ff0000',
		description: 'Color for the active tab.',
	},
	{
		name: 'inactive-color',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_COLOR',
		data: '808080',
		description: 'Color for inactive tabs.',
	},
	{
		name: 'urgent-color',
		path: 'layout:tab-indicator',
		type: 'CONFIG_OPTION_COLOR',
		data: '0000ff',
		description: 'Color for urgent tabs.',
	},

	// --- Insert Hint ---
	{ name: 'insert-hint', path: 'layout', type: 'GROUP', data: '', description: 'Visual feedback for window insertion.' },
	{
		name: 'on',
		path: 'layout:insert-hint',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Enable insertion hints.',
	},
	{
		name: 'off',
		path: 'layout:insert-hint',
		type: 'CONFIG_OPTION_FLAG',
		data: '',
		description: 'Disable insertion hints.',
	},
	{
		name: 'color',
		path: 'layout:insert-hint',
		type: 'CONFIG_OPTION_COLOR',
		data: 'ffc87f80',
		description: 'Color of the insertion hint overlay.',
	},

	// --- Struts ---
	{ name: 'struts', path: 'layout', type: 'GROUP', data: '', description: 'Padding for screen edges to avoid bars/docks.' },
	{ name: 'left', path: 'layout:struts', type: 'CONFIG_OPTION_INT', data: '0, 0, 500', description: 'Left edge strut size.' },
	{ name: 'right', path: 'layout:struts', type: 'CONFIG_OPTION_INT', data: '0, 0, 500', description: 'Right edge strut size.' },
	{ name: 'top', path: 'layout:struts', type: 'CONFIG_OPTION_INT', data: '0, 0, 500', description: 'Top edge strut size.' },
	{ name: 'bottom', path: 'layout:struts', type: 'CONFIG_OPTION_INT', data: '0, 0, 500', description: 'Bottom edge strut size.' },
]
