import type { ConfigDescription } from '@scripts/types/configDescriptionTypes.ts'

export const configDescriptionsExtra: ConfigDescription[] = [
	// -------------------------
	// WindowRuleProps
	// -------------------------
	{
		name: 'match:class',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Windows with class matching RegEx.',
	},
	{
		name: 'match:title',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Windows with title matching RegEx.',
	},
	{
		name: 'match:initial_class',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Windows with initialClass matching RegEx.',
	},
	{
		name: 'match:initial_title',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Windows with initialTitle matching RegEx.',
	},
	{
		name: 'match:tag',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Windows with matching tag.',
	},
	{
		name: 'match:xwayland',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'XWayland windows.',
	},
	{
		name: 'match:float',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Floating windows.',
	},
	{
		name: 'match:fullscreen',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Fullscreen windows.',
	},
	{
		name: 'match:pin',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Pinned windows.',
	},
	{
		name: 'match:focus',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Currently focused window.',
	},
	{
		name: 'match:group',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Grouped windows.',
	},
	{
		name: 'match:modal',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Modal windows (e.g. “Are you sure” popups).',
	},
	{
		name: 'match:fullscreen_state_client',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,3',
		description:
			'Windows with matching fullscreenstate sent to the client (0:none,1:maximize,2:fullscreen,3:both).',
	},
	{
		name: 'match:fullscreen_state_internal',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,3',
		description:
			'Windows with matching internal fullscreenstate (0:none,1:maximize,2:fullscreen,3:both).',
	},
	{
		name: 'match:workspace',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Windows on matching workspace (id, name, or selector).',
	},
	{
		name: 'match:content',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,3',
		description:
			'Windows with specified content type (none=0, photo=1, video=2, game=3).',
	},
	{
		name: 'match:xdg_tag',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Match a window by its xdgTag.',
	},

	// -------------------------
	// Static / Dynamic Effects
	// -------------------------
	{
		name: 'float',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Floats a window.',
	},
	{
		name: 'tile',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Tiles a window.',
	},
	{
		name: 'fullscreen',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Fullscreens a window.',
	},
	{
		name: 'maximize',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Maximizes a window.',
	},
	{
		name: 'fullscreen_state',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,3',
		description: 'Sets fullscreen mode (internal/client).',
	},
	{
		name: 'move',
		path: 'windowrule',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{0,0},{-9999,-9999},{9999,9999}',
		description: 'Moves a floating window to given coordinates.',
	},
	{
		name: 'size',
		path: 'windowrule',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{100,100},{1,1},{9999,9999}',
		description: 'Resizes a floating window.',
	},
	{
		name: 'center',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Centers a floating window on the monitor.',
	},
	{
		name: 'pseudo',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Pseudotiles a window.',
	},
	{
		name: 'monitor',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Sets the monitor for the window (id or name).',
	},
	{
		name: 'workspace',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Sets the workspace for the window.',
	},
	{
		name: 'no_initial_focus',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disables initial focus.',
	},
	{
		name: 'pin',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Pins the window to all workspaces (floating only).',
	},
	{
		name: 'suppress_event',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Ignores specific events (space-separated).',
	},
	{
		name: 'content',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Sets content type (none|photo|video|game).',
	},
	{
		name: 'no_close_for',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,60000',
		description: 'Window uncloseable for given ms.',
	},
	{
		name: 'border_color',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Forces the border color (can include gradients).',
	},
	{
		name: 'opacity',
		path: 'windowrule',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1.0,0.0,1.0',
		description:
			'Overall window opacity (can include active/inactive/fullscreen).',
	},
	{
		name: 'rounding',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,100',
		description: 'Window rounding in pixels.',
	},
	{
		name: 'rounding_power',
		path: 'windowrule',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1.0,0.1,5.0',
		description: 'Overrides the rounding power.',
	},
	{
		name: 'allows_input',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Force window to receive input (XWayland).',
	},
	{
		name: 'dim_around',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Dims everything around the window.',
	},
	{
		name: 'decorate',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Whether to draw window decorations.',
	},
	{
		name: 'focus_on_activate',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'true',
		description: 'Focus app that requests it.',
	},
	{
		name: 'keep_aspect_ratio',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Force aspect ratio when resizing.',
	},
	{
		name: 'nearest_neighbor',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Use nearest neighbor filtering.',
	},
	{
		name: 'no_anim',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disable animations for the window.',
	},
	{
		name: 'no_blur',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disable blur for the window.',
	},
	{
		name: 'no_dim',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disable window dimming.',
	},
	{
		name: 'no_focus',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disable focus to the window.',
	},
	{
		name: 'no_follow_mouse',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Prevent focus when mouse moves over the window.',
	},
	{
		name: 'no_shadow',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disable shadows.',
	},
	{
		name: 'no_shortcuts_inhibit',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disallow app from inhibiting shortcuts.',
	},
	{
		name: 'no_screen_share',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Hide window from screen sharing.',
	},
	{
		name: 'opaque',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Force window to be opaque.',
	},
	{
		name: 'force_rgbx',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Ignore alpha channel on the window.',
	},
	{
		name: 'sync_fullscreen',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Sync fullscreen mode with the window.',
	},
	{
		name: 'immediate',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Force tearing to allow immediate updates.',
	},
	{
		name: 'xray',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Enable blur xray mode.',
	},
	{
		name: 'render_unfocused',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Render window even if not visible.',
	},
	{
		name: 'scroll_mouse',
		path: 'windowrule',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1.0,0.0,10.0',
		description: 'Override mouse scroll factor.',
	},
	{
		name: 'scroll_touchpad',
		path: 'windowrule',
		type: 'CONFIG_OPTION_FLOAT',
		data: '1.0,0.0,10.0',
		description: 'Override touchpad scroll factor.',
	},

	{
		name: 'border_size',
		path: 'windowrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,20',
		description: 'Sets the border size.',
	},
	{
		name: 'animation',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Forces an animation onto a window.',
	},
	{
		name: 'idle_inhibit',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '"none"',
		description: 'Sets idle inhibit mode (none|always|focus|fullscreen).',
	},
	{
		name: 'tag',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Applies or modifies a dynamic tag.',
	},
	{
		name: 'max_size',
		path: 'windowrule',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{0,0},{0,0},{9999,9999}',
		description: 'Sets maximum window size.',
	},
	{
		name: 'min_size',
		path: 'windowrule',
		type: 'CONFIG_OPTION_VECTOR',
		data: '{0,0},{0,0},{9999,9999}',
		description: 'Sets minimum window size.',
	},
	{
		name: 'persistent_size',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Store size for future matching windows.',
	},
	{
		name: 'no_max_size',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Removes maximum size limitations.',
	},
	{
		name: 'stay_focused',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Forces focus while visible.',
	},
	{
		name: 'no_vrr',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disables VRR for the window.',
	},
	{
		name: 'group',
		path: 'windowrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Sets group rule options.',
	},

	// -------------------------
	// Group Rules
	// -------------------------
	{
		name: 'group:set',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Open window as part of a group.',
	},
	{
		name: 'group:new',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Shorthand for barred set.',
	},
	{
		name: 'group:lock',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Lock the group that added this window.',
	},
	{
		name: 'group:barred',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Do not auto-group into focused unlocked group.',
	},
	{
		name: 'group:deny',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Do not allow window to be added to a group.',
	},
	{
		name: 'group:invade',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Force open window in locked group.',
	},
	{
		name: 'group:override',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Override other group rules.',
	},
	{
		name: 'group:unset',
		path: 'windowrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Clear all group rules.',
	},

	{
		name: 'match:namespace',
		path: 'layerrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Match layer namespace.',
	},
	{
		name: 'no_anim',
		path: 'layerrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Disables animations.',
	},
	{
		name: 'blur',
		path: 'layerrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Enable blur.',
	},
	{
		name: 'blur_popups',
		path: 'layerrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Enable blur for popups.',
	},
	{
		name: 'ignore_alpha',
		path: 'layerrule',
		type: 'CONFIG_OPTION_FLOAT',
		data: '0.0,0.0,1.0',
		description: 'Blur ignores pixels below this opacity.',
	},
	{
		name: 'dim_around',
		path: 'layerrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Dim background behind layer.',
	},
	{
		name: 'xray',
		path: 'layerrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,1',
		description: 'Blur xray mode.',
	},
	{
		name: 'animation',
		path: 'layerrule',
		type: 'CONFIG_OPTION_STRING',
		data: '',
		description: 'Set animation style.',
	},
	{
		name: 'order',
		path: 'layerrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,-999,999',
		description: 'Layer z-order.',
	},
	{
		name: 'above_lock',
		path: 'layerrule',
		type: 'CONFIG_OPTION_INT',
		data: '0,0,2',
		description: 'Render above lockscreen.',
	},
	{
		name: 'no_screen_share',
		path: 'layerrule',
		type: 'CONFIG_OPTION_BOOL',
		data: 'false',
		description: 'Hide layer from screen sharing.',
	},
	{
		name: 'bezier',
		path: 'animations',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: 'my-bezier, 0, 0, 1, 1',
		description:
			'Bezier curve defined by its [name] and two control points for use in animation',
	},
	{
		name: 'animation',
		path: 'animations',
		type: 'CONFIG_OPTION_STRING_SHORT',
		data: 'global, 0, 10, 1, 1',
		description:
			'Animation rule following the syntax: [name], [on/off], [speed], [curve], [style].',
	},
	{
		name: 'windowrule',
		path: '',
		type: 'GROUP',
		data: '',
		description: 'A rule',
	},
]
